# This is a basic workflow for CI/CD of JAVA Application

name: Build and Deply Java Application with DevSecOps best practices

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1 - checkout 
        uses: actions/checkout@v2

      # JAVA
      - name: Steup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json"

      # Build
      - name: Build Package
        run: mvn -B package --file pom.xml
        
      # Verify
      - name: Verify package
        run: |
          cd target
          ls -a
